// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using colorbox;

namespace colorbox.Migrations
{
    [DbContext(typeof(ColorBoxDbContext))]
    [Migration("20181111065530_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("colorbox.ColorBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<bool>("IsSelected");

                    b.Property<int>("SessionId");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ColorBoxes");
                });

            modelBuilder.Entity("colorbox.ColorBoxSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastSavedTime");

                    b.HasKey("Id");

                    b.ToTable("ColorBoxSession");
                });

            modelBuilder.Entity("colorbox.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SessionId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("colorbox.ColorBox", b =>
                {
                    b.HasOne("colorbox.ColorBoxSession", "ColorBoxSession")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("colorbox.UserPreference", b =>
                {
                    b.HasOne("colorbox.ColorBoxSession", "ColorBoxSession")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
